services:
  mongo:
    image: mongo:8.0.4
    container_name: daily-bread-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: jhon-the-baptist
      MONGO_INITDB_ROOT_PASSWORD: ABC123
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo-data:/data/db
    network_mode: host
